    - name: Installing Apache
      action: apt pkg=$pkgs state=latest
      with_pkgs:
          - apache2
          - apache2.2-common 
          - apache2-doc 
          - apache2-mpm-prefork 
          - apache2-utils 
          - libexpat1 
          - ssl-cert 
          - mcrypt 
