---
# this is an annotated example of some features available in playbooks
# it shows how to make sure packages are updated, how to make sure
# services are running, and how to template files.  It also demos
# change handlers that can restart things (or trigger other actions)
# when resources change.  For more advanced examples, see example2.yml

# on all hosts, run as the user root...

- name: Base Apps
  hosts: all
  user: teknix
  sudo: yes


  # make these variables available inside of templates
  # for when we use the 'template' action/module later on...

  vars:
    http_port: 80
    max_clients: 200

  # define the tasks that are part of this play...

  tasks:


#  - name: longrunner
#    action: command /bin/sleep 15
#    async: 45
#    poll: 5


#  - name: write some_random_foo configuration
#    action: template src=templates/foo.j2 dest=/etc/some_random_foo.conf
#    notify:
#    - restart apache


  - name: Install Base Package named $item 
    action: apt pkg=$item state=installed
    with_items:
        - rkhunter
        - facter
        - ruby-json
        - rsync
        - logwatch
        - checksecurity
        - fail2ban
  - name: Update Hosts file
    action: template src=templates/etc_hosts.j2 dest=/etc/hosts
